from core.Config import SERVER


def log_exception(exception):
    if SERVER.get("print-errors", True):
        if SERVER.get("print-http-errors", False) or \
            BaseHTTPException not in type(exception).mro():
            print("\033[91mError:", repr(exception), "\033[0m")

class BaseHTTPException(Exception): ...
class BadRequestException(BaseHTTPException): ...
class UnauthorizedException(BaseHTTPException): ...
class ForbiddenException(BaseHTTPException): ...
class NotFoundException(BaseHTTPException): ...
class RequestTimeoutException(BaseHTTPException): ...
class TooManyRequestsException(BaseHTTPException): ...
class InternalException(BaseHTTPException): ...
class ServiceUnavailableException(BaseHTTPException): ...
class TemplateException(Exception): ...
class NoFileException(Exception): ...